USE POSFAPCENTER;

/* Anbar rəhbəri istəyir ki, son 30 gün ərzində hər filial üzrə stokda olan, 
amma heç satılmayan məhsullar müəyyən edilsin. */ 

DECLARE @ENDDATE DATE = '2026-08-18';

WITH STOCK AS(
SELECT 
	ITEMCODE,
	STORAGE,
	SUM(ONHAND) AS STOCK
FROM VW_ERPITEMSTOCK
GROUP BY
	ITEMCODE,
	STORAGE
),
SALES AS(
SELECT 
	INV_OBJ_ID,
	STL_ITMCODE,
	MAX(INV_DATETIME) AS SON_SATIS
FROM OPR_INVOICE
INNER JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
WHERE INV_STATUS = 1
AND INV_TRCODE = 1
GROUP BY
	INV_OBJ_ID,
	STL_ITMCODE
)
SELECT 
	STG_ERPCODE,
	STG_NAME,

	ITM_CODE,
	ITM_NAME,

	ST.STOCK,

	S.SON_SATIS,

	@ENDDATE AS END_DATE,

    DATEDIFF(
        DAY,
        S.SON_SATIS,
        @ENDDATE
    ) AS KECEN_GUN

FROM STOCK ST

INNER JOIN CRD_ITEMS
ON ITM_CODE = ST.ITEMCODE

INNER JOIN CRD_STORAGES
ON STG_ID = ST.STORAGE

LEFT JOIN SALES S
ON S.STL_ITMCODE = ST.ITEMCODE
AND S.INV_OBJ_ID = ST.STORAGE

WHERE ST.STOCK > 0

  AND (
        S.SON_SATIS IS NULL
        OR S.SON_SATIS < DATEADD(DAY, -30, @ENDDATE)
      )

ORDER BY
    STG_ERPCODE,
    ST.STOCK DESC;
