USE POSFAPCENTERPLUS;

/* Hər gün üzrə 
Çek sayi toplam 
Satiş sayi inv_trcode 1
Qaytarma sayi  inv_trcode 2
Toplam satiş */

SELECT 
	CAST(INV_DATETIME AS DATE) AS tarix,
	
	COUNT(INV_FICHENO) AS check_sayi,

	SUM(INV_NETTOTAL) AS INV_NETTOTAL,

	COUNT(CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS satis_sayi,

	COUNT(CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS qaytarma_sayi
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_CLIENTS
ON CLC_CODE = INV_CLCODE
GROUP BY 
	CAST(INV_DATETIME AS DATE);
