USE POSFAPCENTER;

-- Her invoice da nece ferqli mehsul var.
SELECT TOP 100
	INV_FICHENO,
	INV_DATETIME,
	INV_LINECOUNT,
	INV_TERMINAL,
	COUNT(DISTINCT STL_ITMCODE) STL_ITMCODE
	--SUM(STL_AMOUNT) AS STL_AMOUNT,
	--SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	INV_FICHENO,
	INV_DATETIME,
	INV_LINECOUNT,
	INV_TERMINAL
ORDER BY STL_ITMCODE DESC;


-- 102 line 86 ferqli mehsul
SELECT 
	STL_FICHENO,
	STL_AMOUNT,
	STL_RTNFICHENO,
	STL_RTNAMOUNT,
	ITM_CODE,
	ITM_NAME
FROM OPR_STLINE
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
WHERE 
( 
	STL_FICHENO = '001002250420144515'
	OR STL_RTNFICHENO = '001002250420144515'
)
AND STL_TRCODE = 1
AND STL_STATUS = 1;
