USE POSFAPCENTER;

-- Tarix: 01.07.2026 - 31.07.2026
-- 170 NOMRELI MAGAZA

/* Satış direktoru bildirib ki, bəzi filiallarda məhsullar 
stokda olmasına baxmayaraq ümumiyyətlə satılmır.

Anbar şöbəsi həmin məhsulların hansı filiallarda satılmadığını 
müəyyən etmək istəyir ki, məhsullar başqa filiallara köçürülsün. */

WITH SALES AS(
SELECT
	INV_OBJ_ID,
    STL_ITMCODE,
	
	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RTN_CEK,

    SUM(CASE WHEN INV_TRCODE = 1 THEN STL_AMOUNT ELSE 0 END) AS QUANTITY,

	SUM(CASE WHEN INV_TRCODE = 2 THEN STL_RTNAMOUNT ELSE 0 END) AS RTN_QUANTITY,

	SUM(CASE WHEN INV_TRCODE = 1 THEN STL_NETTOTAL ELSE 0 END) AS SATIS_MEBLEG,

    SUM(CASE WHEN INV_TRCODE = 2 THEN STL_NETTOTAL ELSE 0 END) AS QAYTARMA_MEBLEG

FROM OPR_INVOICE 

INNER JOIN OPR_STLINE 
ON STL_FICHENO = INV_FICHENO

WHERE INV_STATUS = 1
AND INV_TRCODE IN (1,2)
AND INV_DATETIME >= '2026-07-01'
AND INV_DATETIME < '2026-08-01'

GROUP BY
     INV_OBJ_ID,
     STL_ITMCODE
),
MEHSUL AS(
SELECT
	STG_ID,
    STG_ERPCODE,
    STG_NAME,

    ITM_CODE,
    ITM_NAME

FROM CRD_STORAGES 
CROSS JOIN CRD_ITEMS 
)
SELECT

    STG_ERPCODE,
    STG_NAME,    

    ITM_CODE,        
    ITM_NAME,         

    ISNULL(S.CEK,0) AS CEK,
	ISNULL(S.RTN_CEK,0) AS RTN_CEK,
	ISNULL(S.QUANTITY,0) AS QUANTITY,
	ISNULL(S.RTN_QUANTITY,0) AS RTN_QUANTITY,
    ISNULL(S.SATIS_MEBLEG,0) AS SATIS_MEBLEG,
	ISNULL(S.QAYTARMA_MEBLEG,0) AS QAYTARMA_MEBLEG,

    CASE
        WHEN ISNULL(S.CEK,0) = 0
            THEN N'Satılmayıb'
        ELSE
            N'Satılıb'
    END AS STATUS

FROM MEHSUL

LEFT JOIN SALES S
ON INV_OBJ_ID = STG_ID
AND STL_ITMCODE = ITM_CODE

WHERE STG_ERPCODE = 170

ORDER BY
	SATIS_MEBLEG DESC;
