USE POSFAPCENTER;

-- 01.06.2026 - 31.07.2026

/* Satış direktoru son 2 ay üzrə filialların məhsul qrupları üzrə performansını analiz etmək istəyir.

Məqsəd yalnız hansı filialın çox satış etdiyini görmək dir. */

WITH MAIN AS(
SELECT 

	STG_ERPCODE,
	STG_NAME,

	GRP_CODE,
	GRP_NAME,

	COUNT(DISTINCT INV_FICHENO) AS CEK,

	COUNT(DISTINCT STL_ITMCODE) AS FERQLI_MEHSUL,

	SUM(STL_AMOUNT) AS QUANTITY,

	SUM(STL_NETTOTAL) AS SATIS_MEBLEGI

FROM OPR_INVOICE

LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO

LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE

LEFT JOIN CRD_ITEMGROUPS
ON GRP_CODE = ITM_GRP_CODE

LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

WHERE INV_STATUS = 1
AND INV_TRCODE = 1
AND INV_DATETIME >= '2026-06-01'
AND INV_DATETIME < '2026-08-01'

GROUP BY
	STG_ERPCODE,
	STG_NAME,

	GRP_CODE,
	GRP_NAME
),
MAGAZA AS(
SELECT *,
	SUM(SATIS_MEBLEGI) OVER(PARTITION BY STG_ERPCODE) AS BRANCH_TOTAL
FROM MAIN
),
FAIZ AS(
SELECT *,
	 ROUND(
        SATIS_MEBLEGI * 100.0 /
        NULLIF(BRANCH_TOTAL,0)
    ,2) AS SALIS_FAIZI

FROM MAGAZA
),
RANKED AS(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY STG_ERPCODE ORDER BY SATIS_MEBLEGI DESC) AS RN
FROM FAIZ
)
SELECT *
FROM RANKED

WHERE RN = 1

ORDER BY 
	STG_ERPCODE ASC,
	SATIS_MEBLEGI DESC
