USE POSFAPCENTER;

-- Hər gün üzrə mağazaların M10 satış və qaytarma statistikası.
SELECT 
	CAST(INV_DATETIME AS date) AS TARIX,
	STG_ERPCODE,
	STG_NAME,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SALES,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RTN_CEK,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS RTN_SALES,

	SUM(CASE WHEN ACO_ACCID = 27 THEN ACO_AMOUNT ELSE 0 END) AS [Nəğdsiz (M10)]
	 
FROM OPR_INVOICE

LEFT JOIN OPR_ACCOUNTS
ON ACO_INVFICHENO = INV_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

WHERE INV_STATUS = 1

GROUP BY
	CAST(INV_DATETIME AS date),
	STG_ERPCODE,
	STG_NAME

ORDER BY TARIX DESC;
