USE POSFAPCENTERPLUS;

/* Satışlar niyə azalıb? */

/* Günlər üzrə satış
→ Hansı gündən sonra düşüş başlayıb? */
WITH CTE AS (SELECT 
	CAST(INV_DATETIME AS date) AS DAY_SALES,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
GROUP BY
	CAST(INV_DATETIME AS date)
)
SELECT	
	DAY_SALES,
	TOTAL_SALES,
	LAG(TOTAL_SALES) OVER(ORDER BY DAY_SALES) AS LAST_DAY_SALES,
	TOTAL_SALES - LAG(TOTAL_SALES) OVER(ORDER BY DAY_SALES) AS DIFF
FROM CTE
ORDER BY DAY_SALES;
