USE POSFAPCENTER;

/* SATIS BANK ILE OLUB YA NEGD
QAYTARMA BANK ILE OLUB YA NEGD*/

-- ACCOUNTS UZRE
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS CASH
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY
	ACO_INVFICHENO,
	ACO_ACCID
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS RTN_BANK,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS RTN_CASH
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY
	ACO_INVFICHENO,
	ACO_ACCID
)
SELECT 
	CAST(I.INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	--COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 THEN I.INV_NETTOTAL ELSE 0 END) AS SATIS,

	--COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 THEN I.INV_NETTOTAL ELSE 0 END) AS QAYTARMA,

	ISNULL(SUM(S.BANK),0) AS BANK,
	ISNULL(SUM(S.CASH),0) AS CASH,
	ISNULL(SUM(Q.RTN_BANK),0) AS RTN_BANK,
	ISNULL(SUM(Q.RTN_CASH),0) AS RTN_CASH

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO
AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO
AND Q.ACO_ACCID = 1 

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1

GROUP BY
	CAST(I.INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO

ORDER BY TARIX DESC, STG_ERPCODE ASC;

-- STLINE UZRE 
WITH SATIS AS(
SELECT 
	STL_FICHENO,
	SUM(STL_AMOUNT) AS STL_QTY,
	SUM(STL_NETTOTAL) AS STL_SATIS
FROM OPR_STLINE
GROUP BY
	STL_FICHENO 
),
QAYTARMA AS(
SELECT 
	STL_RTNFICHENO,
	SUM(STL_RTNAMOUNT) AS STL_RTN_QTY,
	SUM(STL_NETTOTAL) AS STL_QAYTARMA
FROM OPR_STLINE
GROUP BY
	STL_RTNFICHENO 
)
SELECT 
	CAST(I.INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	--COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 THEN I.INV_NETTOTAL ELSE 0 END) AS SATIS,

	--COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 THEN I.INV_NETTOTAL ELSE 0 END) AS QAYTARMA,

	ISNULL(SUM(S.STL_QTY),0) AS STL_QTY,
	ISNULL(SUM(S.STL_SATIS),0) AS STL_SATIS,
	ISNULL(SUM(Q.STL_RTN_QTY),0) AS STL_RTN_QTY,
	ISNULL(SUM(Q.STL_QAYTARMA),0) AS STL_QAYTARMA

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.STL_FICHENO = I.INV_FICHENO
--AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.STL_RTNFICHENO = IR.INV_FICHENO
--AND Q.ACO_ACCID = 1 

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1

GROUP BY
	CAST(I.INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO

ORDER BY TARIX DESC, STG_ERPCODE ASC;
