USE POSFAPCENTER;

-- Sorğu olaraq da wolt satışları çıxar
SELECT DISTINCT
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	INV_CUSTOMERNAME,
	INV_FICHENO,
	INV_RTNFICHENO,
	INV_NETTOTAL,
	USR_NAME
	--ACO_PAYTYPE,
	--ACO_CURRCODE,
	--ACO_CURRAMOUNT

FROM OPR_INVOICE

LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID

LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

LEFT JOIN OPR_ACCOUNTS 
ON ACO_INVFICHENO = INV_FICHENO

WHERE INV_TRCODE = 3
OR INV_TRCODE = 4

--WHERE INV_CUSTOMERNAME LIKE '%WOLT%'

ORDER BY CAST(INV_DATETIME AS DATE);
