USE POSFAPCENTER;

/* Birdə keçən ay ərzində olan 
satış qaytarma 
wolt ayrı 
nəğd ayrı 
bank ayrı. 
Əlavə olaraq qaytarmaları da yaz */

SELECT 
	--SATIS
	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN I.INV_FICHENO END) AS WOLT_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN SLS.ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,
	
	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN I.INV_FICHENO END) AS NEGD_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,

	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN I.INV_FICHENO END) AS BANK_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS BANK_SATIS,

    -- QAYTARMA
	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 10 THEN I.INV_RTNFICHENO END) AS WOLT_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 10 THEN RTN.ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,

	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 2 THEN I.INV_RTNFICHENO END) AS NEGD_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 2 THEN RTN.ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,

	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 1 THEN I.INV_RTNFICHENO END) AS BANK_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 1 THEN RTN.ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA

-- SATIS
FROM OPR_INVOICE I

LEFT JOIN OPR_ACCOUNTS SLS
ON SLS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SBNC.BNC_ID = SLS.ACO_BNCID

-- QAYTARMA
LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN OPR_ACCOUNTS RTN
ON RTN.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY RBNC
ON RBNC.BNC_ID = RTN.ACO_BNCID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1;

-- OR
WITH SALES AS
(
    SELECT
        A.ACO_INVFICHENO,

        SUM(CASE WHEN B.BNC_TYPE = 10 THEN A.ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,
        SUM(CASE WHEN B.BNC_TYPE = 2 THEN A.ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,
        SUM(CASE WHEN B.BNC_TYPE = 1 THEN A.ACO_AMOUNT ELSE 0 END) AS BANK_SATIS

    FROM OPR_ACCOUNTS A
    LEFT JOIN CRD_BANKCURRENCY B
        ON B.BNC_ID = A.ACO_BNCID

    GROUP BY A.ACO_INVFICHENO
),

SALES_COUNT AS
(
    SELECT
        A.ACO_INVFICHENO,

        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 10 THEN A.ACO_INVFICHENO END) AS WOLT_CEK,
        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 2 THEN A.ACO_INVFICHENO END) AS NEGD_CEK,
        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 1 THEN A.ACO_INVFICHENO END) AS BANK_CEK

    FROM OPR_ACCOUNTS A
    LEFT JOIN CRD_BANKCURRENCY B
        ON B.BNC_ID = A.ACO_BNCID

    GROUP BY A.ACO_INVFICHENO
),

RETURNS AS
(
    SELECT
        A.ACO_INVFICHENO,

        SUM(CASE WHEN B.BNC_TYPE = 10 THEN A.ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,
        SUM(CASE WHEN B.BNC_TYPE = 2 THEN A.ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,
        SUM(CASE WHEN B.BNC_TYPE = 1 THEN A.ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA

    FROM OPR_ACCOUNTS A
    LEFT JOIN CRD_BANKCURRENCY B
        ON B.BNC_ID = A.ACO_BNCID

    GROUP BY A.ACO_INVFICHENO
),

RETURNS_COUNT AS
(
    SELECT
        A.ACO_INVFICHENO,

        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 10 THEN A.ACO_INVFICHENO END) AS WOLT_RTN_CEK,
        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 2 THEN A.ACO_INVFICHENO END) AS NEGD_RTN_CEK,
        COUNT(DISTINCT CASE WHEN B.BNC_TYPE = 1 THEN A.ACO_INVFICHENO END) AS BANK_RTN_CEK

    FROM OPR_ACCOUNTS A
    LEFT JOIN CRD_BANKCURRENCY B
        ON B.BNC_ID = A.ACO_BNCID

    GROUP BY A.ACO_INVFICHENO
)

SELECT
    -- SATIŞ COUNT
    ISNULL(CS.WOLT_CEK,0) AS WOLT_CEK,
    ISNULL(CS.NEGD_CEK,0) AS NEGD_CEK,
    ISNULL(CS.BANK_CEK,0) AS BANK_CEK,

    -- SATIŞ SUM
    ISNULL(S.WOLT_SATIS,0) AS WOLT_SATIS,
    ISNULL(S.NEGD_SATIS,0) AS NEGD_SATIS,
    ISNULL(S.BANK_SATIS,0) AS BANK_SATIS,

    -- QAYTARMA COUNT
    ISNULL(RC.WOLT_RTN_CEK,0) AS WOLT_RTN_CEK,
    ISNULL(RC.NEGD_RTN_CEK,0) AS NEGD_RTN_CEK,
    ISNULL(RC.BANK_RTN_CEK,0) AS BANK_RTN_CEK,

    -- QAYTARMA SUM
    ISNULL(R.WOLT_QAYTARMA,0) AS WOLT_QAYTARMA,
    ISNULL(R.NEGD_QAYTARMA,0) AS NEGD_QAYTARMA,
    ISNULL(R.BANK_QAYTARMA,0) AS BANK_QAYTARMA

FROM OPR_INVOICE I

LEFT JOIN SALES S
    ON S.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN SALES_COUNT CS
    ON CS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN OPR_INVOICE IR
    ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN RETURNS R
    ON R.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN RETURNS_COUNT RC
    ON RC.ACO_INVFICHENO = IR.INV_FICHENO

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1;

--OR
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	--SATIS
    SUM(CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN SLS.ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,

    SUM(CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,

    SUM(CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS BANK_SATIS,

    -- QAYTARMA
    SUM(CASE WHEN RBNC.BNC_TYPE = 10 THEN RTN.ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,

    SUM(CASE WHEN RBNC.BNC_TYPE = 2 THEN RTN.ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,

    SUM(CASE WHEN RBNC.BNC_TYPE = 1 THEN RTN.ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA,

	USR_NAME

FROM OPR_INVOICE I

LEFT JOIN OPR_ACCOUNTS SLS
ON SLS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SBNC.BNC_ID = SLS.ACO_BNCID

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN OPR_ACCOUNTS RTN
ON RTN.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY RBNC
ON RBNC.BNC_ID = RTN.ACO_BNCID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1

GROUP BY 
    I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,
	USR_NAME
	 
ORDER BY INV_DATETIME ASC;

-- OR*
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(CASE WHEN BNC_TYPE = 10 THEN ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK_SATIS
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(DISTINCT CASE WHEN BNC_TYPE = 10 THEN ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,
	SUM(DISTINCT CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,
	SUM(DISTINCT CASE WHEN BNC_TYPE = 1  THEN ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID
)
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	ISNULL(S.WOLT_SATIS, 0) AS WOLT_SATIS,
	ISNULL(S.NEGD_SATIS, 0) AS NEGD_SATIS,
	ISNULL(S.BANK_SATIS,0) AS BANK_SATIS,

	ISNULL(Q.WOLT_QAYTARMA, 0) AS WOLT_QAYTARMA,
	ISNULL(Q.NEGD_QAYTARMA, 0) AS NEGD_QAYTARMA,
	ISNULL(Q.BANK_QAYTARMA, 0) AS BANK_QAYTARMA,

	USR_NAME

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO
AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO
AND Q.ACO_ACCID = 1

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1

ORDER BY I.INV_DATETIME ASC;
