USE [POSFAPCENTERPLUS]
GO

/****** Object:  Table [dbo].[OPR_ACCOUNTS]    Script Date: 4/22/2026 1:54:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OPR_ACCOUNTS](
	[ACO_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACO_ACOID] [int] NULL,
	[ACO_TYPE] [int] NULL,
	[ACO_STGID] [int] NULL,
	[ACO_CSCID] [int] NULL,
	[ACO_TERMINAL] [varchar](50) NULL,
	[ACO_USRID] [int] NULL,
	[ACO_ACCID] [int] NULL,
	[ACO_DATE] [datetime] NULL,
	[ACO_INVFICHENO] [varchar](50) NULL,
	[ACO_AMOUNT] [decimal](18, 2) NULL,
	[ACO_STATUS] [int] NULL,
	[ACO_NOTE] [nvarchar](250) NULL,
	[ACO_ISSEND] [int] NULL,
	[ACO_SENDDATE] [datetime] NULL,
	[ACO_CRUSER] [int] NULL,
	[ACO_CRDATE] [datetime] NULL,
	[ACO_MDUSER] [int] NULL,
	[ACO_MDDATE] [datetime] NULL,
	[ACO_PAYTYPE] [int] NULL,
	[ACO_BNCID] [int] NULL,
	[ACO_CURRCODE] [varchar](50) NULL,
	[ACO_CURRRATE] [decimal](18, 5) NULL,
	[ACO_CURRAMOUNT] [decimal](18, 2) NULL,
	[ACO_CACOID] [int] NULL,
	[ACO_DOCUMENTID] [varchar](50) NULL,
	[ACO_DOCNUMBER] [int] NULL,
	[ACO_SHIFTDOCNUMBER] [int] NULL,
	[ACO_SHORTDOCID] [varchar](50) NULL,
	[ACO_POSRRN] [varchar](50) NULL,
	[ACO_POSTRNID] [int] NULL,
	[ACO_POSTRANSACTIONID] [varchar](50) NULL,
	[ACO_POSPAN] [varchar](50) NULL,
	[ACO_POSSENDAMOUNT] [varchar](50) NULL,
 CONSTRAINT [PK_OPR_ACCOUNTS_2020] PRIMARY KEY CLUSTERED 
(
	[ACO_ID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
