USE POSFAPCENTER;

/* Son 6 ayda hansa kasada en cox satis olub negd ve bank */

WITH CTE AS
(
SELECT
	INV_FICHENO,
	USR_NAME,
	INV_NETTOTAL,
	INV_TRCODE
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE INV_DATETIME >= DATEADD(MONTH, -6, GETDATE())
AND INV_STATUS = 1
),
CTE2 AS
(
SELECT
	ACO_INVFICHENO,
	ACO_TERMINAL,

	SUM(CASE WHEN ACO_ACCID = 3 THEN ACO_AMOUNT ELSE 0 END) AS NEGD,
	SUM(CASE WHEN ACO_ACCID = 6 THEN ACO_AMOUNT ELSE 0 END) AS [ABB BANK],
	SUM(CASE WHEN ACO_ACCID = 7 THEN ACO_AMOUNT ELSE 0 END) AS [PASA BANK],
	SUM(CASE WHEN ACO_ACCID = 28 THEN ACO_AMOUNT ELSE 0 END) AS [XALQ BANK]
FROM OPR_ACCOUNTS
GROUP BY
	ACO_INVFICHENO,
	ACO_TERMINAL
)
SELECT
	USR_NAME,
	ACO_TERMINAL,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK_SAYI,
	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RETURN_CEK,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS TOTAL_SALES,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS TOTAL_RETURN,

	SUM(NEGD) AS NEGD,
	SUM([ABB BANK]) AS [ABB BANK],
	SUM([PASA BANK]) AS [PASA BANK],
	SUM([XALQ BANK]) AS [XALQ BANK]

FROM CTE C1
LEFT JOIN CTE2 C2
ON C2.ACO_INVFICHENO = C1.INV_FICHENO
GROUP BY
	USR_NAME,
	ACO_TERMINAL
ORDER BY TOTAL_SALES DESC;
