USE POSFAPCENTER;

-- 01.07.2026 - 31.07.2026

/* Maliyyə şöbəsi son 1 ay ərzində kassirlərin performansını yoxlamaq istəyir.

Məqsəd hansı kassirin daha çox əməliyyat etdiyini yox, 

hansı kassirin daha yüksək satış həcmi yaratdığını 

və geri qaytarmalarının çox olub-olmadığını müəyyən etməkdir. */

WITH STLINE AS(
SELECT 
	STL_FICHENO,
	SUM(STL_AMOUNT) AS QUANTITY,
	SUM(STL_RTNAMOUNT) AS RTN_QUANTITY
FROM OPR_STLINE
GROUP BY
	STL_FICHENO
)
SELECT 
	USR_CODE,
	USR_NAME,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_RTNFICHENO END) AS RTN_CEK,

	SUM(CASE WHEN INV_TRCODE = 1 THEN S.QUANTITY ELSE 0 END) AS QUANTITY,

	SUM(CASE WHEN INV_TRCODE = 2 THEN S.RTN_QUANTITY ELSE 0 END) AS RTN_QUANTITY,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS_MEBLEG,

	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARMA_MEBLEG,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END)
	- SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS NET_MEBLEG,

	ROUND(
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) 
	/ NULLIF(COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END),0)
	,2) AS ORTA_CEK_MEBLEG

FROM OPR_INVOICE

LEFT JOIN STLINE S
ON S.STL_FICHENO = INV_FICHENO

LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID

WHERE INV_STATUS = 1
AND INV_TRCODE IN (1,2)
AND INV_DATETIME >= '2026-07-01'
AND INV_DATETIME < '2026-08-01'

GROUP BY
	USR_CODE,
	USR_NAME

HAVING SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END)
	- SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) > 5000
	AND COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) >= 30

ORDER BY
	NET_MEBLEG DESC,
	CEK DESC
