USE POSFAPCENTERPLUS;

/* Hər məhsul qrupu üzrə:
ümumi satış məbləği
satılan miqdar
satış sayı (çek sayı)
ən gəlirli kassir */
WITH CTE AS(
SELECT 
	USR_NAME,
	GRP_NAME,
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS TOTAL_SALES,
	SUM(CASE WHEN INV_TRCODE = 1 THEN STL_AMOUNT ELSE 0 END) AS TOTAL_QUANTITY,
	COUNT(CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CHECK_SAYI,
	COUNT(CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RETURN_SAYI
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
LEFT JOIN CRD_ITEMGROUPS
ON GRP_CODE = ITM_GRP_CODE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
GROUP BY
	USR_NAME,
	GRP_NAME
),
CTE2 AS(
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY GRP_NAME 
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
)
SELECT *
FROM CTE2;
