USE POSFAPCENTER;

/* 01.07.2026 – 22.07.2026 tarixləri arasında filial və kassir üzrə 
gündəlik satış performansı hazırlanmalıdır. */

WITH ACCOUNTS AS(
SELECT 
	ACO_INVFICHENO,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS CASH
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
WHERE ACO_ACCID = 1
GROUP BY
	ACO_INVFICHENO
),
STLINE AS(
SELECT 
	STL_FICHENO,
	SUM( CASE WHEN STL_TRCODE = 1 THEN STL_AMOUNT ELSE 0 END) AS SATILA_MEHSUL,
	SUM( CASE WHEN STL_TRCODE = 2 THEN STL_RTNAMOUNT ELSE 0 END) AS QAYTARILAN_MEHSUL
FROM OPR_STLINE
WHERE STL_STATUS = 1 
GROUP BY
	STL_FICHENO
)
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE AS MAGAZA_CODE,
	STG_NAME AS MAGAZA_ADI,
	USR_NAME AS KASSIR,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS SATIS_CEK,
	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS QAYTARMA_CEK,

	ISNULL(SUM(S.SATILA_MEHSUL),0) AS SATILAN_MEHSUL,
	ISNULL(SUM(S.QAYTARILAN_MEHSUL),0) AS QAYTARILAN_MEHSUL,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_TOTAL ELSE 0 END) AS ESIL_MEBLEGI,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_DISCOUNTS ELSE 0 END) AS UMUMI_ENDIRIM,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS_MEBLEGI,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_TOTAL ELSE 0 END) AS QAYTARMA_MEBLEGI,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) -
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS XALIS_MEBLEG,

	ISNULL(SUM(A.BANK),0) AS BANK,
	ISNULL(SUM(A.CASH),0) AS CASH,
	SUM(INV_BONUSTOTAL) AS BONUS,

	CASE 
	WHEN 
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) -
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) >= 5000 THEN 'Excellent'
	WHEN 
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) -
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) >= 3000 THEN 'Good'
	WHEN 
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) -
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) >= 1000 THEN 'Average'
	ELSE 'Low'
	END AS STATUS
	
FROM OPR_INVOICE

LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID

LEFT JOIN ACCOUNTS A
ON A.ACO_INVFICHENO = INV_FICHENO

LEFT JOIN STLINE S
ON S.STL_FICHENO = INV_FICHENO

WHERE INV_STATUS = 1
AND INV_TRCODE IN (1,2)
AND INV_DATETIME >= '2026-07-01'
AND INV_DATETIME < '2026-07-23'

GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	USR_NAME

ORDER BY
	TARIX,
	STG_ERPCODE;
