USE POSFAPCENTERPLUS;

-- 3 Tip
/* Hər gün üzrə ən çox satış edən kassirin hesabatı. */ 
SELECT *
FROM (
SELECT 
	CAST(INV_DATETIME AS DATE) AS SALES_DATE,
	USR_NAME,
	SUM(INV_NETTOTAL) AS TOTAL_SALES,
	COUNT(INV_FICHENO) AS CEK_SAYI,
	ROW_NUMBER() OVER(
	PARTITION BY CAST(INV_DATETIME AS DATE)
	ORDER BY SUM(INV_NETTOTAL) DESC
	) AS RN
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	CAST(INV_DATETIME AS DATE),
	USR_NAME
) T
WHERE RN = 1;

--OR
WITH CTE AS(
SELECT 
	CAST(INV_DATETIME AS DATE) AS SALES_DATE,
	USR_NAME,
	SUM(INV_NETTOTAL) AS TOTAL_SALES,
	COUNT(INV_FICHENO) AS CEK_SAYI
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	CAST(INV_DATETIME AS DATE),
	USR_NAME
),
CTE2 AS(
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY SALES_DATE
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
)
SELECT *
FROM CTE2
WHERE RN = 1;

--OR
WITH CTE AS(
SELECT 
	CAST(INV_DATETIME AS DATE) AS SALES_DATE,
	USR_NAME,
	SUM(INV_NETTOTAL) AS TOTAL_SALES,
	COUNT(INV_FICHENO) AS CEK_SAYI
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	CAST(INV_DATETIME AS DATE),
	USR_NAME
)
SELECT *
FROM (
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY SALES_DATE
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
) T
WHERE RN = 1;
