USE POSFAPCENTERPLUS;

-- “Ən çox satış edən kassir və məhsullar”
-- CREATE VIEW VW_CASHIER_SALES_REPORT AS
WITH MAIN AS(
SELECT 
	USR_NAME,
	CSC_NAME,
	INV_FICHENO,
	STL_ITMCODE,
	ITM_NAME,
	STL_AMOUNT,
	STL_PRICE
FROM OPR_INVOICE

LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO

LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID

LEFT JOIN CRD_CASHBOX
ON CSC_ID = INV_CSC_ID

LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE

WHERE INV_DATETIME >= DATEADD(DAY, -70, GETDATE())
AND INV_TRCODE = 1
AND INV_STATUS = 1
),
CEKLER AS(
SELECT DISTINCT
	USR_NAME,
	INV_FICHENO
FROM MAIN
),
CEK_LIST AS(
SELECT 
	USR_NAME,
	STRING_AGG(CAST(INV_FICHENO AS VARCHAR(MAX)), ', ') AS CEKLER
FROM CEKLER
GROUP BY
	USR_NAME
),
PRODUCTS AS(
SELECT DISTINCT	
	USR_NAME,
	STL_ITMCODE
FROM MAIN
),
PRODUCT_LIST AS(
SELECT 
	USR_NAME,
	STRING_AGG(CAST(STL_ITMCODE AS VARCHAR(MAX)), ', ') AS MEHSULLAR
FROM PRODUCTS
GROUP BY
	USR_NAME
),
PRODUCT_COUNT AS(
SELECT 
	USR_NAME,
	ITM_NAME,
	COUNT(*) AS SATIS_SAYI
	FROM MAIN
	GROUP BY 
		USR_NAME,
		ITM_NAME
),
TOP_PRODUCTS AS (
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY USR_NAME
ORDER BY SATIS_SAYI DESC
) AS RN
FROM PRODUCT_COUNT
),
TOP3_PRODUCTS AS(
SELECT 
	USR_NAME,
	STRING_AGG(CAST(ITM_NAME AS VARCHAR(MAX)), ', ') AS TOP_3_PRODUCTS
FROM TOP_PRODUCTS
WHERE RN <= 3
GROUP BY
	USR_NAME
)
SELECT 
	M.USR_NAME,
	M.CSC_NAME,
	COUNT(DISTINCT M.INV_FICHENO) AS CEK_SAYI,
	CL.CEKLER,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES,
	COUNT(M.STL_ITMCODE) AS MEHSUL_SAYI,
	PL.MEHSULLAR,
	TP.TOP_3_PRODUCTS
FROM MAIN M

LEFT JOIN CEK_LIST CL
ON CL.USR_NAME = M.USR_NAME

LEFT JOIN PRODUCT_LIST PL
ON PL.USR_NAME = M.USR_NAME

LEFT JOIN TOP3_PRODUCTS TP
ON TP.USR_NAME = M.USR_NAME

GROUP BY
	M.USR_NAME,
	M.CSC_NAME,
	CL.CEKLER,
	PL.MEHSULLAR,
	TP.TOP_3_PRODUCTS

-- ORDER BY TOTAL_SALES DESC;
