USE POSFAPCENTERPLUS;

/* Satışlar niyə azalıb? */

/* Məhsul üzrə satış
→ Hansı məhsulların satışı azalıb? */
WITH CTE AS(
SELECT 
	ITM_CODE,
	ITM_NAME,
	CAST(INV_DATETIME AS DATE) AS DAY_SALES,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
WHERE STL_TRCODE = 1
GROUP BY
	ITM_CODE,
	ITM_NAME,
	CAST(INV_DATETIME AS DATE)
)
SELECT 
	ITM_CODE,
	DAY_SALES,
	TOTAL_SALES,
	LAG(TOTAL_SALES) OVER(PARTITION BY ITM_CODE ORDER BY DAY_SALES) AS LAST_DAY_SALES,
	TOTAL_SALES - LAG(TOTAL_SALES) OVER(PARTITION BY ITM_CODE ORDER BY DAY_SALES) AS DIFF
FROM CTE
ORDER BY ITM_CODE, DAY_SALES;
