USE POSFAPCENTERPLUS;

/* Hər müştəri üzrə:
ümumi alış məbləği
alış sayı (neçə çek)
qaytarma sayı
ən son alış tarixi
son 30 gündə etdiyi alış məbləği */
SELECT 
	CLC_NAME,
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL else 0 END) AS TOTAL_SALES,
	COUNT(CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CHECK_SAYI,
	COUNT(CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RETURN_SAYI,
	MAX(CASE WHEN INV_TRCODE = 1 THEN INV_DATETIME END) AS LAST_SALES,
	SUM(
	CASE
	WHEN INV_TRCODE = 1
	AND INV_DATETIME >= DATEADD(DAY, -60, GETDATE()) 
	THEN INV_NETTOTAL ELSE 0 END
	) AS LAST_60DAYS_SALES
FROM OPR_INVOICE
LEFT JOIN CRD_CLIENTS
ON CLC_CODE = INV_CLCODE
GROUP BY 
	CLC_NAME;
