USE POSFAPCENTER;

-- 01.02.2026 - 31.07.2026

/* Marketing şöbəsi son 6 ay ərzində müştərilərin alış davranışını analiz etmək istəyir.

Onlar yalnız çox pul xərcləyən müştəriləri deyil, 

eyni zamanda şirkətə davamlı gəlir gətirən müştəriləri müəyyən etmək istəyirlər. */

WITH CLIENTS AS(
SELECT 
	CLC_CODE,
	CLC_NAME,

	COUNT(DISTINCT INV_FICHENO) AS CEK,

	SUM(INV_NETTOTAL) AS SATIS_MEBLEGI,

	COUNT(DISTINCT CAST (INV_DATETIME AS date)) AS ALIS_FERQL_GUN,

	COUNT(DISTINCT YEAR(INV_DATETIME) * 100 + MONTH(INV_DATETIME)) AS ALIS_FERQLI_AY,

	SUM(INV_NETTOTAL) / NULLIF(COUNT(DISTINCT INV_FICHENO),0)  AS ORTA_CEK_MEBLEGI,
	
	MAX(INV_NETTOTAL) AS BOYUK_CEK_MEBLEGI,

	MIN(INV_NETTOTAL) AS KICIK_CEK_MEBLEGI

FROM OPR_INVOICE

LEFT JOIN CRD_CLIENTS
ON CLC_CODE = INV_CLCODE

WHERE INV_STATUS = 1
AND INV_TRCODE = 1
AND INV_DATETIME >= '2026-02-01'
AND INV_DATETIME < '2026-08-01'

GROUP BY
	CLC_CODE,
	CLC_NAME
),
CLIENTS_STATUS AS(
SELECT *,

	CASE 
	WHEN ALIS_FERQLI_AY >= 5
	AND ALIS_FERQL_GUN >= 15
	AND SATIS_MEBLEGI >= 1500 THEN 'Platinum'

	WHEN ALIS_FERQLI_AY >= 4
	AND SATIS_MEBLEGI >= 1000 THEN 'Gold'

	WHEN SATIS_MEBLEGI >= 500 THEN 'Silver'

	ELSE 'Bronze'
	END AS SCORE

FROM CLIENTS
),
RANKED AS(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY SCORE ORDER BY SATIS_MEBLEGI DESC) AS RN 
FROM CLIENTS_STATUS
)
SELECT 
	CLC_CODE,
	CLC_NAME,

	CEK,
	SATIS_MEBLEGI,

	ALIS_FERQL_GUN,
	ALIS_FERQLI_AY,

	ORTA_CEK_MEBLEGI,
	BOYUK_CEK_MEBLEGI,
	KICIK_CEK_MEBLEGI,

	SCORE,
	RN

FROM RANKED

-- WHERE RN = 1

ORDER BY SATIS_MEBLEGI DESC
