USE POSFAPCENTER;

/* Satış rəhbəri istəyir ki, son 30 gün ərzində heç bir satış etməyən aktiv müştərilər müəyyən edilsin. */

DECLARE @ENDDATE DATE = '2026-08-18';

SELECT 
	CLC_CODE,
	CLC_NAME,

	MAX(INV_DATETIME) AS SON_SATIS,

	@ENDDATE AS END_DATE,

	DATEDIFF(
    DAY,
    MAX(INV_DATETIME),
    @ENDDATE
) AS KECEN_GUN

FROM CRD_CLIENTS

LEFT JOIN OPR_INVOICE
ON INV_CLCODE = CLC_CODE
AND INV_STATUS = 1
AND INV_TRCODE = 1

WHERE CLC_STATUS = 1

GROUP BY
	CLC_CODE,
	CLC_NAME

HAVING 
	MAX(INV_DATETIME) IS NULL
	OR MAX(INV_DATETIME) < DATEADD(DAY, -30, @ENDDATE)

ORDER BY KECEN_GUN DESC;
