USE POSFAPCENTER;

/* Aprel ayında bank ilə ödənilən satışlar üzrə nəğd qaytarma əməliyyatlarını çıxarın.
Bank satış məbləği və qaytarılan nəğd məbləğ göstərilsin. */
SELECT DISTINCT
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,
	INV_FICHENO,
	INV_RTNFICHENO,
	INV_DATETIME,

	SBNC.BNC_CODE AS BANK_SATIS,
	SLS.ACO_AMOUNT AS BANK_MEBLEG,

	RBNC.BNC_CODE AS CASH_QAYTARMA,
	RTN.ACO_AMOUNT*-1 AS CASH_MEBLEG

FROM OPR_INVOICE

LEFT JOIN OPR_ACCOUNTS SLS
ON INV_RTNFICHENO = SLS.ACO_INVFICHENO
AND SLS.ACO_AMOUNT > 0
AND SLS.ACO_STATUS = 1

LEFT JOIN OPR_ACCOUNTS RTN
ON INV_FICHENO = RTN.ACO_INVFICHENO
AND RTN.ACO_AMOUNT < 0
AND RTN.ACO_STATUS = 1

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SLS.ACO_BNCID = SBNC.BNC_ID

LEFT JOIN CRD_BANKCURRENCY RBNC 
ON RTN.ACO_BNCID = RBNC.BNC_ID

LEFT JOIN CRD_STORAGES
ON INV_OBJ_ID = STG_ID

LEFT JOIN SYS_USERS_
ON INV_USR_ID = USR_ID

WHERE INV_TRCODE = 2 
AND INV_STATUS = 1
AND INV_DATETIME >= '2026-05-01' 
AND INV_DATETIME <= '2026-05-31'
--AND INV_DATETIME BETWEEN '2026-05-01' AND '2026-05-30'
AND RTN.ACO_BNCID <> SLS.ACO_BNCID 

ORDER BY INV_DATETIME, INV_FICHENO;


-- AND Q
SELECT 
	STG_ERPCODE, 
	STG_NAME, 
	USR_NAME, 
	INV_RTNFICHENO,
	INV_FICHENO, 
	INV_DATETIME, 
	BNC.BNC_CODE AS QAYTARMA_ODEME, 
	ACO.ACO_AMOUNT*-1 AS QAYTARMA_MEBLEG, 
	SBN.BNC_CODE AS SALES_ODEME, 
	SLS.ACO_AMOUNT AS  SALES_MEBLEG 

FROM OPR_INVOICE WITH(NOLOCK) 

LEFT JOIN OPR_ACCOUNTS ACO WITH(NOLOCK) 
ON (INV_OBJ_ID = ACO.ACO_STGID 
AND INV_CSC_ID = ACO.ACO_CSCID 
AND INV_FICHENO = ACO.ACO_INVFICHENO)

LEFT JOIN CRD_BANKCURRENCY BNC 
ON (ACO.ACO_BNCID = BNC.BNC_ID)

LEFT JOIN CRD_STORAGES 
ON (INV_OBJ_ID = STG_ID)

LEFT JOIN SYS_USERS_ USR 
ON (INV_USR_ID = USR_ID)

LEFT JOIN OPR_ACCOUNTS ASL WITH(NOLOCK) 
ON (INV_RTNFICHENO = ASL.ACO_INVFICHENO 
AND ASL.ACO_TYPE = 1 
AND ASL.ACO_STATUS = 1 
AND NOT ASL.ACO_ACCID IN (1,2) 
AND ACO.ACO_BNCID = ASL.ACO_BNCID 
AND ASL.ACO_AMOUNT > 0)

LEFT JOIN OPR_ACCOUNTS SLS WITH(NOLOCK) 
ON (INV_RTNFICHENO = SLS.ACO_INVFICHENO 
AND SLS.ACO_TYPE = 1 
AND SLS.ACO_STATUS = 1 
AND NOT SLS.ACO_ACCID IN (1,2) 
AND SLS.ACO_AMOUNT > 0)

LEFT JOIN CRD_BANKCURRENCY SBN 
ON (SLS.ACO_BNCID = SBN.BNC_ID)

WHERE INV_TRCODE = 2 
AND INV_STATUS = 1 
AND INV_DATETIME >= '2025-12-01' 
AND INV_DATETIME <= '2025-12-11' and NOT ACO.ACO_ACCID IN (1,2)  
AND ACO.ACO_AMOUNT < 0 
AND ISNULL(ASL.ACO_ID,0) <= 0 AND ACO.ACO_BNCID <> SLS.ACO_BNCID

ORDER BY INV_DATETIME, INV_FICHENO;
