USE POSFAPCENTER;

/* PAR ilə başlayan RRN nömrəsi olan və bank tərəfindən təsdiqlənmiş satışlar. */
SELECT 
	INV_FICHENO, 
	INV_DATETIME, 
	INV_STARTTIME, 
	INV_STOPTIME, 
	INV_NETTOTAL, 
	BNK_FICHENO, 
	BNK_RRN, 
	BNK_TRNSTATUS,
	ACO_AMOUNT
FROM OPR_INVOICE
LEFT JOIN OPR_BANK
ON INV_FICHENO = BNK_FICHENO
left join OPR_ACCOUNTS
on ACO_INVFICHENO = INV_FICHENO
WHERE BNK_RRN LIKE 'PAR%'
AND BNK_TRNSTATUS = 'approved';
