USE POSFAPCENTER;

/* PAR ilə başlayan RRN nömrəsi olan və bank tərəfindən təsdiqlənmiş satışlar. */
SELECT 
	INV_FICHENO, 
	INV_DATETIME, 
	INV_STARTTIME, 
	INV_STOPTIME, 
	INV_NETTOTAL, 
	BNK_FICHENO, 
	BNK_RRN, 
	BNK_TRNSTATUS,
	ACO_AMOUNT
FROM OPR_INVOICE
LEFT JOIN OPR_BANK
ON INV_FICHENO = BNK_FICHENO
left join OPR_ACCOUNTS
on ACO_INVFICHENO = INV_FICHENO
WHERE BNK_RRN LIKE 'PAR%'
AND BNK_TRNSTATUS = 'approved';

--OR SELF JOIN
SELECT 
	INV_FICHENO, 
	INV_DATETIME, 
	INV_STARTTIME, 
	INV_STOPTIME, 
	INV_NETTOTAL, 
	BNK_FICHENO, 
	BNK_RRN, 
	BNK_TRNSTATUS,
	a1.ACO_ACCID as NEGD,
	a2.ACO_ACCID AS BANK
FROM OPR_INVOICE
LEFT JOIN OPR_BANK
ON INV_FICHENO = BNK_FICHENO
left join OPR_ACCOUNTS a1
on a1.ACO_INVFICHENO = INV_FICHENO
left join OPR_ACCOUNTS a2
on a2.ACO_INVFICHENO = INV_FICHENO
WHERE BNK_RRN LIKE 'PAR%'
AND BNK_TRNSTATUS = 'approved'
AND A1.ACO_ACCID = 3
AND A2.ACO_ACCID IN (6,7,28);

-- OR
SELECT 
	INV_FICHENO, 
	INV_DATETIME, 
	INV_STARTTIME, 
	INV_STOPTIME, 
	INV_NETTOTAL, 
	BNK_FICHENO, 
	BNK_RRN, 
	BNK_TRNSTATUS,
	SUM(CASE WHEN ACO_ACCID = 3 THEN ACO_AMOUNT ELSE 0 END) AS NEGD,
	SUM(CASE WHEN ACO_ACCID = 6 THEN ACO_AMOUNT ELSE 0 END) AS [ABB BANK],
	SUM(CASE WHEN ACO_ACCID = 7 THEN ACO_AMOUNT ELSE 0 END) AS [PASHA BANK],
	SUM(CASE WHEN ACO_ACCID = 28 THEN ACO_AMOUNT ELSE 0 END) AS [XALQ BANK],
	SUM(CASE WHEN ACO_ACCID = 22 THEN ACO_AMOUNT ELSE 0 END) AS [UniBank]

FROM OPR_INVOICE
LEFT JOIN OPR_BANK
ON INV_FICHENO = BNK_FICHENO
left join OPR_ACCOUNTS
on ACO_INVFICHENO = INV_FICHENO
WHERE BNK_RRN LIKE 'PAR%'
AND BNK_TRNSTATUS = 'approved'
GROUP BY
	INV_FICHENO, 
	INV_DATETIME, 
	INV_STARTTIME, 
	INV_STOPTIME, 
	INV_NETTOTAL, 
	BNK_FICHENO, 
	BNK_RRN, 
	BNK_TRNSTATUS;
