USE POSFAPCENTER;

/* Ay ərzində olan bank, nağd, M10, umico bonus 
bütün satış və qaytarmalari */

SELECT 
	'SATIS' AS SATIS,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 1 THEN I.INV_FICHENO END) AS BANK_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS BANK_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 2 THEN I.INV_FICHENO END) AS NEGD_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 2 THEN SLS.ACO_AMOUNT ELSE 0 END) AS NEGD_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 8 THEN I.INV_FICHENO END) AS M10_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 8 THEN SLS.ACO_AMOUNT ELSE 0 END) AS M10_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 4 THEN I.INV_FICHENO END) AS UMICO_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 1 AND SBNC.BNC_TYPE = 4 THEN SLS.ACO_AMOUNT ELSE 0 END) AS UMICO_MEBLEG,

	'QAYTARMA' AS QAYTARMA,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 1 THEN I.INV_FICHENO END) AS BANK_RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 1 THEN RTN.ACO_AMOUNT ELSE 0 END) AS BANK_RTN_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 2 THEN I.INV_FICHENO END) AS NEGD_RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 2 THEN RTN.ACO_AMOUNT ELSE 0 END) AS NEGD_RTN_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 8 THEN I.INV_FICHENO END) AS M10_RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 8 THEN RTN.ACO_AMOUNT ELSE 0 END) AS M10_RTN_MEBLEG,

	COUNT(DISTINCT CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 4 THEN I.INV_FICHENO END) AS UMICO_RTN_CEK,
	SUM(CASE WHEN I.INV_TRCODE = 2 AND RBNC.BNC_TYPE = 4 THEN RTN.ACO_AMOUNT ELSE 0 END) AS UMICO_RTN_MEBLEG

-- SATIS
FROM OPR_INVOICE I

LEFT JOIN OPR_ACCOUNTS SLS
ON SLS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SBNC.BNC_ID = SLS.ACO_BNCID

-- QAYTARMA
LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN OPR_ACCOUNTS RTN
ON RTN.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY RBNC
ON RBNC.BNC_ID = RTN.ACO_BNCID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1;

-- OR
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 8 THEN ACO_AMOUNT ELSE 0 END) AS M10_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 4 THEN ACO_AMOUNT ELSE 0 END) AS UMICO_MEBLEG
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK_RTN_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_RTN_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 8 THEN ACO_AMOUNT ELSE 0 END) AS M10_RTN_MEBLEG,
	SUM(CASE WHEN BNC_TYPE = 4 THEN ACO_AMOUNT ELSE 0 END) AS UMICO_RTN_MEBLEG
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID
)
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_CLCARDCODE,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	ISNULL(S.BANK_MEBLEG, 0) AS BANK_MEBLEG,
	ISNULL(S.NEGD_MEBLEG, 0) AS NEGD_MEBLEG,
	ISNULL(S.M10_MEBLEG,0) AS M10_MEBLEG,
	ISNULL(S.UMICO_MEBLEG, 0) AS UMICO_MEBLEG,

	ISNULL(Q.BANK_RTN_MEBLEG, 0) AS BANK_RTN_MEBLEG,
	ISNULL(Q.NEGD_RTN_MEBLEG, 0) AS NEGD_RTN_MEBLEG,
	ISNULL(Q.M10_RTN_MEBLEG, 0) AS M10_RTN_MEBLEG,
	ISNULL(Q.UMICO_RTN_MEBLEG, 0) AS UMICO_RTN_MEBLEG,

	USR_NAME

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO
AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO
AND Q.ACO_ACCID = 1

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1

ORDER BY I.INV_DATETIME ASC;
