USE POSFAPCENTER;

/* 128787 bu kodlu mehsulun aprel ayi uzre bonus kartlar ile ne qeder satis olunub
ve ne qeder qaytarma olunub */
--*
WITH SATIS AS(
SELECT 
	STL_ITMCODE,
	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS CEK,
	SUM(STL_AMOUNT) AS SATIS_MIQDAR,
	SUM(STL_AMOUNT * STL_PRICE) AS SATIS_MEBLEG
FROM OPR_STLINE
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
WHERE INV_STATUS = 1
AND MONTH(INV_DATETIME) = 4
GROUP BY STL_ITMCODE
),
QAYTARMA AS(
SELECT 
	STL_ITMCODE,
	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_RTNFICHENO END) AS RTN_CEK,
	SUM(STL_RTNAMOUNT) AS QAYTARMA_MIQDAR,
	SUM(STL_RTNAMOUNT * STL_PRICE) AS QAYTARMA_MEBLEG
FROM OPR_STLINE
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
WHERE INV_STATUS = 1
AND MONTH(INV_DATETIME) = 4
GROUP BY STL_ITMCODE
)
SELECT 

	'128787' AS ITM_CODE,

	ISNULL(S.CEK, 0) AS CEK,
	ISNULL(S.SATIS_MIQDAR, 0) AS SATIS_MIQDAR,
	ISNULL(S.SATIS_MEBLEG, 0) AS SATIS_MEBLEG,

	ISNULL(Q.RTN_CEK, 0) AS RTN_CEK,
	ISNULL(Q.QAYTARMA_MIQDAR, 0) AS QAYTARMA_MIQDAR,
	ISNULL(Q.QAYTARMA_MEBLEG, 0) AS QAYTARMA_MEBLEG

FROM SATIS S
LEFT JOIN QAYTARMA Q
ON Q.STL_ITMCODE = S.STL_ITMCODE
WHERE S.STL_ITMCODE = '128787'
OR Q.STL_ITMCODE = '128787';

-- OR
SELECT

	COUNT(CASE WHEN ISLS.INV_TRCODE = 1 THEN ISLS.INV_FICHENO END) AS CEK,
    SUM(CASE WHEN ISLS.INV_TRCODE = 1 THEN SSLS.STL_AMOUNT ELSE 0 END) AS SATIS_MIQDAR,
    SUM(CASE WHEN ISLS.INV_TRCODE = 1 THEN SSLS.STL_AMOUNT * SSLS.STL_PRICE ELSE 0 END) AS SATIS_MEBLEG,

	COUNT(CASE WHEN IRTN.INV_TRCODE = 2 THEN IRTN.INV_RTNFICHENO END) AS RTN_CEK,
    SUM(CASE WHEN IRTN.INV_TRCODE = 2 THEN SRTN.STL_RTNAMOUNT ELSE 0 END) AS QAYTARMA_MIQDAR,
    SUM(CASE WHEN IRTN.INV_TRCODE = 2 THEN SRTN.STL_RTNAMOUNT * SRTN.STL_PRICE ELSE 0 END) AS QAYTARMA_MEBLEG

FROM CRD_ITEMS I

LEFT JOIN OPR_STLINE SSLS
ON SSLS.STL_ITMCODE = I.ITM_CODE

LEFT JOIN OPR_INVOICE ISLS
ON ISLS.INV_FICHENO = SSLS.STL_FICHENO


LEFT JOIN CRD_ITEMS IR
ON IR.ITM_CODE = I.ITM_CODE

LEFT JOIN OPR_STLINE SRTN
ON SRTN.STL_ITMCODE = IR.ITM_CODE

LEFT JOIN OPR_INVOICE IRTN
ON IRTN.INV_FICHENO = SRTN.STL_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = ISLS.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = ISLS.INV_USR_ID

LEFT JOIN CRD_CLIENTS
ON CLC_CODE = ISLS.INV_CLCODE


WHERE I.ITM_CODE = '128787'
AND MONTH(ISLS.INV_DATETIME) = 4
AND ISLS.INV_STATUS = 1;

--OR
SELECT

	STG_ERPCODE,
	STG_NAME,
    I.ITM_CODE,
    I.ITM_NAME,
	CLC_NAME,
	CLC_CARDCODE,
	CLC_BONUSTOTAL,
	CLC_BONUSUSED,
	ISLS.INV_CLCARDCODE,
	ISLS.INV_FICHENO,
	ISLS.INV_RTNFICHENO,
	USR_NAME,

	COUNT(CASE WHEN ISLS.INV_TRCODE = 1 THEN ISLS.INV_FICHENO END) AS CEK,
    SUM(CASE WHEN ISLS.INV_TRCODE = 1 THEN SSLS.STL_AMOUNT ELSE 0 END) AS SATIS_MIQDAR,
    SUM(CASE WHEN ISLS.INV_TRCODE = 1 THEN SSLS.STL_AMOUNT * SSLS.STL_PRICE ELSE 0 END) AS SATIS_MEBLEG,

	COUNT(CASE WHEN IRTN.INV_TRCODE = 2 THEN IRTN.INV_RTNFICHENO END) AS RTN_CEK,
    SUM(CASE WHEN IRTN.INV_TRCODE = 2 THEN SRTN.STL_RTNAMOUNT ELSE 0 END) AS QAYTARMA_MIQDAR,
    SUM(CASE WHEN IRTN.INV_TRCODE = 2 THEN SRTN.STL_RTNAMOUNT * SRTN.STL_PRICE ELSE 0 END) AS QAYTARMA_MEBLEG

FROM CRD_ITEMS I

LEFT JOIN OPR_STLINE SSLS
ON SSLS.STL_ITMCODE = I.ITM_CODE

LEFT JOIN OPR_INVOICE ISLS
ON ISLS.INV_FICHENO = SSLS.STL_FICHENO


LEFT JOIN CRD_ITEMS IR
ON IR.ITM_CODE = I.ITM_CODE

LEFT JOIN OPR_STLINE SRTN
ON SRTN.STL_ITMCODE = IR.ITM_CODE

LEFT JOIN OPR_INVOICE IRTN
ON IRTN.INV_FICHENO = SRTN.STL_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = ISLS.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = ISLS.INV_USR_ID

LEFT JOIN CRD_CLIENTS
ON CLC_CODE = ISLS.INV_CLCODE


WHERE I.ITM_CODE = '128787'
AND MONTH(ISLS.INV_DATETIME) = 4
AND ISLS.INV_STATUS = 1
--AND  CLC_CARDCODE IS NOT NULL

GROUP BY
	STG_ERPCODE,
	STG_NAME,
    I.ITM_CODE,
    I.ITM_NAME,
	CLC_NAME,
	CLC_CARDCODE,
	CLC_BONUSTOTAL,
	CLC_BONUSUSED,
	ISLS.INV_CLCARDCODE,
	ISLS.INV_FICHENO,
	ISLS.INV_RTNFICHENO,
	USR_NAME;


-- OR CTE*
WITH SALES AS (
    SELECT 
        I.ITM_CODE,
        I.ITM_NAME,
        ISLS.INV_FICHENO,
        ISLS.INV_CLCARDCODE,
        USR_NAME,
        STG_ERPCODE,
        STG_NAME,

        SUM(SSLS.STL_AMOUNT) AS SATIS_MIQDAR,
        SUM(SSLS.STL_AMOUNT * SSLS.STL_PRICE) AS SATIS_MEBLEG

    FROM CRD_ITEMS I
    LEFT JOIN OPR_STLINE SSLS 
        ON SSLS.STL_ITMCODE = I.ITM_CODE
    LEFT JOIN OPR_INVOICE ISLS 
        ON ISLS.INV_FICHENO = SSLS.STL_FICHENO
    LEFT JOIN CRD_STORAGES 
        ON STG_ID = ISLS.INV_OBJ_ID
    LEFT JOIN SYS_USERS_ 
        ON USR_ID = ISLS.INV_USR_ID

    WHERE I.ITM_CODE = '128787'
      AND ISLS.INV_TRCODE = 1
      AND ISLS.INV_STATUS = 1
      AND MONTH(ISLS.INV_DATETIME) = 4

    GROUP BY 
        I.ITM_CODE,
        I.ITM_NAME,
        ISLS.INV_FICHENO,
        ISLS.INV_CLCARDCODE,
        USR_NAME,
        STG_ERPCODE,
        STG_NAME
),

RETURNS AS (
    SELECT 
        I.ITM_CODE,
        ISLS.INV_RTNFICHENO,

        SUM(SRTN.STL_RTNAMOUNT) AS QAYTARMA_MIQDAR,
        SUM(SRTN.STL_RTNAMOUNT * SRTN.STL_PRICE) AS QAYTARMA_MEBLEG

    FROM CRD_ITEMS I
    LEFT JOIN OPR_STLINE SRTN 
        ON SRTN.STL_ITMCODE = I.ITM_CODE
    LEFT JOIN OPR_INVOICE ISLS 
        ON ISLS.INV_FICHENO = SRTN.STL_FICHENO

    WHERE I.ITM_CODE = '128787'
      AND ISLS.INV_TRCODE = 2
      AND ISLS.INV_STATUS = 1
      AND MONTH(ISLS.INV_DATETIME) = 4

    GROUP BY 
        I.ITM_CODE,
        ISLS.INV_RTNFICHENO
)

SELECT 
    S.STG_ERPCODE,
    S.STG_NAME,
    S.ITM_CODE,
    S.ITM_NAME,
    S.USR_NAME,
    S.INV_FICHENO,
    S.INV_CLCARDCODE,

    COUNT(S.INV_FICHENO) AS CEK_SAYI,
    SUM(S.SATIS_MIQDAR) AS SATIS_MIQDAR,
    SUM(S.SATIS_MEBLEG) AS SATIS_MEBLEG,

    COUNT(R.INV_RTNFICHENO) AS RTN_CEK,
    SUM(R.QAYTARMA_MIQDAR) AS QAYTARMA_MIQDAR,
    SUM(R.QAYTARMA_MEBLEG) AS QAYTARMA_MEBLEG

FROM SALES S
LEFT JOIN RETURNS R
    ON R.ITM_CODE = S.ITM_CODE
    AND R.INV_RTNFICHENO = S.INV_FICHENO

GROUP BY 
    S.STG_ERPCODE,
    S.STG_NAME,
    S.ITM_CODE,
    S.ITM_NAME,
    S.USR_NAME,
    S.INV_FICHENO,
    S.INV_CLCARDCODE;
