USE POSFAPCENTERPLUS;

/* Satışlar niyə azalıb? */

/* Kassir üzrə satış
→ Hansı kassir az satıb? */
WITH CTE AS(
SELECT 
	USR_NAME,
	CAST(INV_DATETIME AS DATE) AS DAY_SALES,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE STL_TRCODE = 1
GROUP BY 
	USR_NAME,
	CAST(INV_DATETIME AS DATE)
)
SELECT 
	USR_NAME,
	DAY_SALES,
	TOTAL_SALES,
	LAG(TOTAL_SALES) OVER(PARTITION BY USR_NAME ORDER BY DAY_SALES) AS LAST_DAY_SALES,
	TOTAL_SALES - LAG(TOTAL_SALES) OVER(PARTITION BY USR_NAME ORDER BY DAY_SALES) AS DIFF
FROM CTE
ORDER BY USR_NAME, DAY_SALES;
