USE POSFAPCENTERPLUS;

/* Hər gün üzrə TOP kassir */
WITH CTE AS(
SELECT 
	CAST(INV_DATETIME AS date) AS DAY_SALES,
	SUM(INV_NETTOTAL) AS TOTAL_SALES,
	USR_NAME
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
WHERE INV_TRCODE = 1
GROUP BY 
	USR_NAME,
	CAST(INV_DATETIME AS date)
),
CTE2 AS (
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY DAY_SALES
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
)
SELECT *
FROM CTE2;
