USE POSFAPCENTER;

/* Zəhmət olmasa, 03.07.2026 tarixi üzrə 
bütün filialların satış və qaytarma məbləğini çıxar. */

-- INV_NETTOTAL
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARMA

FROM OPR_INVOICE
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE INV_STATUS = 1
AND INV_DATETIME >= '2026-07-03'
AND INV_DATETIME < '2026-07-04'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME
ORDER BY TARIX DESC, STG_ERPCODE ASC;

-- ACO_ACCOUNT 
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,

	SUM(CASE WHEN ACO_ACCID = 1 THEN B.ACO_AMOUNT ELSE 0 END) AS ACO_SATIS,
	SUM(CASE WHEN ACO_ACCID = 2 THEN B.ACO_AMOUNT ELSE 0 END) AS ACO_QAYTARMA

FROM OPR_INVOICE
LEFT JOIN (
SELECT 
	ACO_INVFICHENO,
	ACO_AMOUNT,
	ACO_ACCID
FROM OPR_ACCOUNTS
)B
ON B.ACO_INVFICHENO = INV_FICHENO
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE INV_STATUS = 1
AND INV_DATETIME >= '2026-07-03'
AND INV_DATETIME < '2026-07-04'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME
ORDER BY TARIX DESC, STG_ERPCODE ASC;

-- OR
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_AMOUNT,
	ACO_ACCID
FROM OPR_ACCOUNTS
)
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,

	SUM(CASE WHEN ACO_ACCID = 1 THEN B.ACO_AMOUNT ELSE 0 END) AS ACO_SATIS,
	SUM(CASE WHEN ACO_ACCID = 2 THEN B.ACO_AMOUNT ELSE 0 END) AS ACO_QAYTARMA

FROM OPR_INVOICE
LEFT JOIN SATIS B
ON B.ACO_INVFICHENO = INV_FICHENO
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE INV_STATUS = 1
AND INV_DATETIME >= '2026-07-03'
AND INV_DATETIME < '2026-07-04'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME
ORDER BY TARIX DESC, STG_ERPCODE ASC;
