 USE POSFAPCENTERPLUS;

/* MAGAZANIN CODE, ADI 
MART AYINI GORE
SATIS SAYI
QAYTARMA SAYI*/

SELECT 
	STG_CODE,
	STG_NAME,
	MONTH(INV_DATETIME) AS MONTH_SALES,
	COUNT(CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS SATIS_SAYI,
	COUNT(CASE WHEN INV_TRCODE = 2 THEN INV_FICHENO END) AS RETURN_SAYI,
	CASE WHEN MONTH(INV_DATETIME) = 3 THEN 'MART' END AS STATUS
FROM OPR_INVOICE
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE MONTH(INV_DATETIME) = '03'
GROUP BY
	STG_CODE,
	STG_NAME,
	MONTH(INV_DATETIME),
	FORMAT(INV_DATETIME, 'yyyy-MM');
