USE POSFAPCENTER;

/* Sual: Satış və qaytarma üzrə ödənişlərini göstərin. */
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE,
	SUM(ACO_AMOUNT) AS TOTAL_SATIS
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE,
	SUM(ACO_AMOUNT) AS TOTAL_QAYTARMA
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE
)
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,

	S.BNC_CODE,
	ISNULL((S.TOTAL_SATIS),0) AS SATIS,
	Q.BNC_CODE,
	ISNULL((Q.TOTAL_QAYTARMA),0) AS QAYTARMA

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO
AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO
AND Q.ACO_ACCID = 1

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1
AND I.INV_DATETIME >= '2026-06-30'
AND S.BNC_CODE IS NOT NULL

ORDER BY I.INV_DATETIME DESC;


-- AND
/* Sual: Çeklər üzrə satış, qaytarma, ƏDV və ƏDV-siz məbləğləri göstərin. */
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,

	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS,

	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARMA,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_VATAMNT ELSE 0 END) AS EDV,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_VATMATRAH ELSE 0 END) AS EDVSIZ

FROM OPR_INVOICE I

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1
AND I.INV_DATETIME >= '2026-06-30'

GROUP BY
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,
	I.INV_FICHENO,
	I.INV_RTNFICHENO

ORDER BY I.INV_DATETIME DESC;
