USE POSFAPCENTER;

/* Sual: Satış və qaytarma üzrə ödənişlərini göstərin. */
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE,
	SUM(ACO_AMOUNT) AS TOTAL_SATIS
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE,
	SUM(ACO_AMOUNT) AS TOTAL_QAYTARMA
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO,
	ACO_ACCID,
	BNC_CODE
)
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,

	S.BNC_CODE,
	ISNULL((S.TOTAL_SATIS),0) AS SATIS,
	Q.BNC_CODE,
	ISNULL((Q.TOTAL_QAYTARMA),0) AS QAYTARMA

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO
AND S.ACO_ACCID = 1

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO
AND Q.ACO_ACCID = 1

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1
AND I.INV_DATETIME >= '2026-06-30'
AND S.BNC_CODE IS NOT NULL

ORDER BY I.INV_DATETIME DESC;


-- AND
/* Sual: Çeklər üzrə satış, qaytarma, ƏDV və ƏDV-siz məbləğləri göstərin. */
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,

	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS,

	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARMA,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_VATAMNT ELSE 0 END) AS EDV,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_VATMATRAH ELSE 0 END) AS EDVSIZ

FROM OPR_INVOICE I

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

WHERE I.INV_STATUS = 1
AND I.INV_DATETIME >= '2026-06-30'

GROUP BY
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
    USR_NAME,
	I.INV_CLCARDCODE,
	I.INV_FICHENO,
	I.INV_RTNFICHENO

ORDER BY I.INV_DATETIME DESC;

-- STL_SATIS, INV_SATIS
SELECT 
	INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,
	INV_CLCARDCODE,
	INV_FICHENO,
	INV_RTNFICHENO,

	COUNT(DISTINCT STL_ITMCODE) AS MEHSULUN_SAYI,

	SUM(CASE WHEN INV_TRCODE = 1 THEN STL_AMOUNT ELSE 0 END) AS QTY,
	SUM(CASE WHEN INV_TRCODE = 2 THEN STL_RTNAMOUNT ELSE 0 END) AS RTN_QTY,

	SUM(CASE WHEN INV_TRCODE = 1 THEN STL_NETTOTAL ELSE 0 END) AS STL_SATIS,
	SUM(CASE WHEN INV_TRCODE = 2 THEN STL_NETTOTAL ELSE 0 END) AS STL_QAYTARMA,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS INV_SATIS,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS INV_QAYTARMA,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_VATAMNT ELSE 0 END) AS EDV,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_VATMATRAH ELSE 0 END) AS EDVSIZ

FROM OPR_INVOICE

LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID

WHERE INV_STATUS = 1
AND INV_DATETIME >= '2026-07-01'

GROUP BY
	INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,
	INV_CLCARDCODE,
	INV_FICHENO,
	INV_RTNFICHENO

ORDER BY INV_DATETIME DESC;

-- Hansi mehsulun satisi dir (STRING_AGG) ile
WITH MAIN AS (
SELECT
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,   
	I.INV_CLCARDCODE,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,
	I.INV_TRCODE,
	I.INV_NETTOTAL,
	I.INV_VATAMNT,
	I.INV_VATMATRAH,
	STL_AMOUNT,
	STL_RTNAMOUNT,
	STL_PRICE,
	STL_ITMCODE
FROM OPR_INVOICE I

LEFT JOIN OPR_STLINE
ON STL_FICHENO = I.INV_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_STATUS = 1
AND I.INV_DATETIME >= '2026-07-02'
),

MEHSULLAR AS (
SELECT DISTINCT
	INV_FICHENO,
	STL_ITMCODE
FROM MAIN
),

MEHSUL_LIST AS (
SELECT
	INV_FICHENO,
	STRING_AGG(CAST(STL_ITMCODE AS VARCHAR(MAX)), ', ') AS MEHSULLAR
FROM MEHSULLAR
GROUP BY INV_FICHENO
)
SELECT
	M.INV_DATETIME,
	M.STG_ERPCODE,
	M.STG_NAME,
	M.USR_NAME,
	M.INV_CLCARDCODE,

	M.INV_FICHENO AS CEKLER,
	M.INV_RTNFICHENO,

	SUM(CASE WHEN M.INV_TRCODE = 1 THEN M.STL_AMOUNT ELSE 0 END) AS QTY,
	SUM(CASE WHEN M.INV_TRCODE = 2 THEN M.STL_RTNAMOUNT ELSE 0 END) AS RTN_QTY,

	SUM(CASE WHEN M.INV_TRCODE = 1 THEN M.STL_PRICE ELSE 0 END) AS PRICE,
	SUM(CASE WHEN M.INV_TRCODE = 2 THEN M.STL_PRICE ELSE 0 END) AS RTN_PRICE,

	SUM(CASE WHEN M.INV_TRCODE = 1 THEN M.STL_AMOUNT * M.STL_PRICE ELSE 0 END) AS STL_SATIS_MEBLEG,
	SUM(CASE WHEN M.INV_TRCODE = 2 THEN M.STL_RTNAMOUNT * M.STL_PRICE ELSE 0 END) AS STL_QAYTARMA_MEBLEG,

	SUM(CASE WHEN M.INV_TRCODE = 1 THEN M.INV_NETTOTAL ELSE 0 END) AS INV_SATIS_MEBLEG,
	SUM(CASE WHEN M.INV_TRCODE = 2 THEN M.INV_NETTOTAL ELSE 0 END) AS INV_QAYTARMA_MEBLEG,

	SUM(CASE WHEN M.INV_TRCODE = 1 THEN M.INV_VATAMNT ELSE 0 END) AS EDV,
	SUM(CASE WHEN M.INV_TRCODE = 2 THEN M.INV_VATMATRAH ELSE 0 END) AS EDVSIZ,

	ML.MEHSULLAR
FROM MAIN M

LEFT JOIN MEHSUL_LIST ML
ON ML.INV_FICHENO = M.INV_FICHENO

GROUP BY
	M.INV_DATETIME,
	M.STG_ERPCODE,
	M.STG_NAME,
	M.USR_NAME,
	M.INV_CLCARDCODE,
	M.INV_FICHENO,
	M.INV_RTNFICHENO,
	ML.MEHSULLAR

ORDER BY
	M.INV_DATETIME DESC;
