USE POSFAPCENTER;

-- Hər mağaza üzrə günlük satış və qaytarma əməliyyatlarını, nisyə satışları, endirimləri, ƏDV məbləğini və ƏDV-siz gəliri hesablayan SQL hesabatı yazın.

SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 1 THEN INV_FICHENO END) AS SATIS_CEK,
	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END) AS SATIS,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 2 THEN INV_RTNFICHENO END) AS QAYTARMA_CEK,
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARMA,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 3 THEN INV_FICHENO END) AS NISYE_CEK,
	SUM(CASE WHEN INV_TRCODE = 3 THEN INV_NETTOTAL ELSE 0 END) AS NISYE_SATIS_NET,

	COUNT(DISTINCT CASE WHEN INV_TRCODE = 4 THEN INV_RTNFICHENO END) AS NISYE_RTN_CEK,
	SUM(CASE WHEN INV_TRCODE = 4 THEN INV_NETTOTAL ELSE 0 END) AS NISYE_QAYTARMA_NET,

	SUM(INV_DISCOUNTS) AS UMUMI_ENDIRIM,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_NETTOTAL ELSE 0 END)
	-
	SUM(CASE WHEN INV_TRCODE = 2 THEN INV_NETTOTAL ELSE 0 END)
	+
	SUM(CASE WHEN INV_TRCODE = 3 THEN INV_NETTOTAL ELSE 0 END)
	-
	SUM(CASE WHEN INV_TRCODE = 4 THEN INV_NETTOTAL ELSE 0 END) AS QAYTARILMA_CIXILDIQDAN_SONRA_YEKUN,

	SUM(CASE WHEN INV_TRCODE = 1 THEN INV_VATAMNT ELSE 0 END) AS UMUMI_EDV_MEBLEGI,

    SUM(CASE WHEN INV_TRCODE = 1 THEN INV_VATMATRAH ELSE 0 END) AS UMUMI_EDV_SIZ_MEBLEG

FROM OPR_INVOICE
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID

WHERE INV_STATUS = 1
AND MONTH(INV_DATETIME) = '5'

GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME

ORDER BY TARIX, STG_ERPCODE ASC;
