USE POSFAPCENTER;

/* Zəhmət olmasa 05.07.2026 tarixi üzrə hər mağazada ən çox satılan 5 məhsulu çıxar. */
WITH SATIS AS(
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	ITM_CODE,
	ITM_NAME,
	SUM(STL_AMOUNT) AS QTY,
	SUM(STL_PRICE) AS PRICE,
	SUM(STL_NETTOTAL) AS TOTAL_SATIS
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE INV_STATUS = 1
AND INV_TRCODE = 1
AND INV_DATETIME >= '2026-07-05'
AND INV_DATETIME < '2026-07-06'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	ITM_CODE,
	ITM_NAME
),
RANKED AS(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY STG_ERPCODE ORDER BY TOTAL_SATIS DESC) AS RN
FROM SATIS
)
SELECT 
	TARIX,
    STG_ERPCODE,
    STG_NAME,
    ITM_CODE,
    ITM_NAME,
    QTY,
    PRICE,
    TOTAL_SATIS
FROM RANKED  
WHERE RN <= 5
ORDER BY STG_ERPCODE, RN ASC;

-- SADICE 1001 OLAN MAGAZANIN SATISI
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	ITM_CODE,
	ITM_NAME,
	SUM(STL_AMOUNT) AS QTY,
	SUM(STL_PRICE) AS PRICE,
	SUM(STL_NETTOTAL) AS TOTAL_SATIS
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
WHERE INV_STATUS = 1
AND INV_TRCODE = 1
AND INV_DATETIME >= '2026-07-05'
AND INV_DATETIME < '2026-07-06'
AND STG_ERPCODE = '1001'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	ITM_CODE,
	ITM_NAME
ORDER BY TOTAL_SATIS DESC;
