USE POSFAPCENTER;

/* Zəhmət olmasa, 07.07.2026 tarixi üzrə hər mağazada ən çox satış edən 3 kassiri çıxar. */
WITH SATIS AS(
SELECT 
	CAST(INV_DATETIME AS DATE) AS TARIX,
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,
	COUNT(DISTINCT INV_FICHENO) AS CEK,
	COUNT(DISTINCT STL_ITMCODE) AS MEHSULUN_SAYI,
	SUM(STL_AMOUNT) AS QTY,
	SUM(STL_NETTOTAL) AS SATIS
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_STORAGES
ON STG_ID = INV_OBJ_ID
LEFT JOIN SYS_USERS_
ON USR_ID = INV_USR_ID
WHERE INV_STATUS = 1
AND INV_TRCODE = 1
AND INV_DATETIME >= '2026-07-07'
AND INV_DATETIME < '2026-07-08'
GROUP BY
	CAST(INV_DATETIME AS DATE),
	STG_ERPCODE,
	STG_NAME,
	USR_NAME
),
RANKED AS (
SELECT *,
ROW_NUMBER() OVER(PARTITION BY STG_ERPCODE ORDER BY SATIS DESC) AS RN
FROM SATIS
)
SELECT 
	TARIX,
	STG_ERPCODE,
	STG_NAME,
	USR_NAME,
	CEK,
	MEHSULUN_SAYI,
	QTY,
	SATIS,
	RN AS SIRA
FROM RANKED
WHERE RN <= 3
ORDER BY
    STG_ERPCODE,
    RN;
