USE POSFAPCENTERPLUS;

-- 3 tip
/* Hər kassir üzrə ən çox satılan məhsul */
SELECT *
FROM(
SELECT 
	USR_NAME,
	ITM_CODE,
	ITM_NAME,
	SUM(STL_AMOUNT) AS TOTAL_AMOUNT,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES,
	ROW_NUMBER() OVER(
	PARTITION BY USR_NAME
	ORDER BY SUM(STL_AMOUNT * STL_PRICE) DESC
	) AS RN
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	USR_NAME,
	ITM_CODE,
	ITM_NAME
) T
WHERE RN = 1;

-- OR
WITH CTE AS(
SELECT 
	USR_NAME,
	ITM_CODE,
	ITM_NAME,
	SUM(STL_AMOUNT) AS TOTAL_AMOUNT,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	USR_NAME,
	ITM_CODE,
	ITM_NAME
),
CTE2 AS(
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY USR_NAME
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
)
SELECT * 
FROM CTE2
WHERE RN = 1;

--OR
WITH CTE AS(
SELECT 
	USR_NAME,
	ITM_CODE,
	ITM_NAME,
	SUM(STL_AMOUNT) AS TOTAL_AMOUNT,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM OPR_INVOICE
LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID
LEFT JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
WHERE INV_TRCODE = 1
AND INV_STATUS = 1
GROUP BY
	USR_NAME,
	ITM_CODE,
	ITM_NAME
)
SELECT *
FROM(
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY USR_NAME
ORDER BY TOTAL_SALES DESC
) AS RN
FROM CTE
) T
WHERE RN = 1;
