USE POSFAPCENTERPLUS;

/* SATIS VE QAYTARMA NI KIM EDIB  */
-- CREATE VIEW VW_InvoiceFullReport AS 
WITH Payment AS(
SELECT 
	ACO_INVFICHENO,
	MAX(CASE WHEN ACO_ACCID = 3 THEN 'NEGD' END) AS NEGD,
	MAX(CASE WHEN ACO_ACCID = 6  THEN 'ABB BANK' END) AS [ABB BANK],
	MAX(CASE WHEN ACO_ACCID = 7  THEN 'PASH BANK' END) AS [PASHA BANK],
	MAX(CASE WHEN ACO_ACCID = 28  THEN 'XALQ BANK' END) AS [XALQ BANK]
FROM OPR_ACCOUNTS
GROUP BY
	ACO_INVFICHENO
),
ProductBase AS(
SELECT DISTINCT
	STL_FICHENO,
	ITM_NAME,
	ITM_CODE
FROM OPR_STLINE
LEFT JOIN CRD_ITEMS
ON ITM_CODE = STL_ITMCODE
),
Products AS(
SELECT 
	STL_FICHENO,
	
    STRING_AGG(CAST(ITM_NAME AS NVARCHAR(MAX)), ', ') AS PRODUCT_NAMES,
    STRING_AGG(CAST(ITM_CODE AS NVARCHAR(MAX)), ', ') AS PRODUCT_CODES,

    COUNT(*) AS PRODUCT_COUNT
FROM ProductBase
GROUP BY 
	STL_FICHENO
)
SELECT 
	INV_FICHENO,
	INV_RTNFICHENO,
	INV_DATETIME,
	INV_NETTOTAL,

	CASE 
		WHEN INV_TRCODE = 1 THEN 'SATIS'
		WHEN INV_TRCODE = 2 THEN 'QAYTARMA'
	END AS STATUS,

	USR_NAME,
	CLC_NAME,

/*  CASE 
		WHEN INV_TRCODE = 1 THEN CLC_NAME
	END AS SATIS_EDEN,

	CASE 
		WHEN INV_TRCODE = 2 THEN CLC_NAME
	END AS QAYTARMA_EDEN, */

	PRODUCT_NAMES,
	PRODUCT_CODES,
	PRODUCT_COUNT,

	NEGD,
	[ABB BANK],
	[PASHA BANK],
	[XALQ BANK]

FROM OPR_INVOICE

LEFT JOIN Products
ON STL_FICHENO = INV_FICHENO

LEFT JOIN Payment
ON ACO_INVFICHENO = INV_FICHENO

LEFT JOIN SYS_USERS_
ON USR_CSCID = INV_CSC_ID

LEFT JOIN CRD_CLIENTS
ON CLC_CODE = INV_CLCODE

--ORDER BY INV_DATETIME DESC;
