USE POSFAPCENTER;

/* Birdə keçən ay ərzində olan 
satış qaytarma 
wolt ayrı 
nəğd ayrı 
bank ayrı. 
Əlavə olaraq qaytarmaları da yaz */

SELECT 
	--SATIS
	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN I.INV_FICHENO END) AS WOLT_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN SLS.ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,
	
	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN I.INV_FICHENO END) AS NEGD_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,

	COUNT(DISTINCT CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN I.INV_FICHENO END) AS BANK_CEK,
    SUM(CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS BANK_SATIS,

    -- QAYTARMA
	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 10 THEN I.INV_RTNFICHENO END) AS WOLT_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 10 THEN RTN.ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,

	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 2 THEN I.INV_RTNFICHENO END) AS NEGD_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 2 THEN RTN.ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,

	COUNT(DISTINCT CASE WHEN RBNC.BNC_TYPE = 1 THEN I.INV_RTNFICHENO END) AS BANK_RTN_CEK,
    SUM(CASE WHEN RBNC.BNC_TYPE = 1 THEN RTN.ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA

-- SATIS
FROM OPR_INVOICE I

LEFT JOIN OPR_ACCOUNTS SLS
ON SLS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SBNC.BNC_ID = SLS.ACO_BNCID

-- QAYTARMA
LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN OPR_ACCOUNTS RTN
ON RTN.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY RBNC
ON RBNC.BNC_ID = RTN.ACO_BNCID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1;

--OR
WITH SATIS AS(
SELECT 
	ACO_INVFICHENO,
	SUM(CASE WHEN BNC_TYPE = 10 THEN ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK_SATIS
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO
),
QAYTARMA AS(
SELECT 
	ACO_INVFICHENO,
	SUM(CASE WHEN BNC_TYPE = 10 THEN ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,
	SUM(CASE WHEN BNC_TYPE = 2 THEN ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,
	SUM(CASE WHEN BNC_TYPE = 1 THEN ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA
FROM OPR_ACCOUNTS
LEFT JOIN CRD_BANKCURRENCY
ON BNC_ID = ACO_BNCID
GROUP BY 
	ACO_INVFICHENO
)
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	ISNULL(S.WOLT_SATIS, 0) AS WOLT_SATIS,
	ISNULL(S.NEGD_SATIS, 0) AS NEGD_SATIS,
	ISNULL(S.BANK_SATIS,0) AS BANK_SATIS,

	ISNULL(Q.WOLT_QAYTARMA, 0) AS WOLT_QAYTARMA,
	ISNULL(Q.NEGD_QAYTARMA, 0) AS NEGD_QAYTARMA,
	ISNULL(Q.BANK_QAYTARMA, 0) AS BANK_QAYTARMA,

	USR_NAME

FROM OPR_INVOICE I

LEFT JOIN SATIS S
ON S.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN QAYTARMA Q
ON Q.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1

ORDER BY I.INV_DATETIME ASC;

--OR
SELECT 
	I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,

	--SATIS
    SUM(CASE WHEN SBNC.BNC_TYPE = 10 AND I.INV_TRCODE = 3 THEN SLS.ACO_AMOUNT ELSE 0 END) AS WOLT_SATIS,

    SUM(CASE WHEN SBNC.BNC_TYPE = 2 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS NEGD_SATIS,

    SUM(CASE WHEN SBNC.BNC_TYPE = 1 AND I.INV_TRCODE = 1 THEN SLS.ACO_AMOUNT ELSE 0 END) AS BANK_SATIS,

    -- QAYTARMA
    SUM(CASE WHEN RBNC.BNC_TYPE = 10 THEN RTN.ACO_AMOUNT ELSE 0 END) AS WOLT_QAYTARMA,

    SUM(CASE WHEN RBNC.BNC_TYPE = 2 THEN RTN.ACO_AMOUNT ELSE 0 END) AS NEGD_QAYTARMA,

    SUM(CASE WHEN RBNC.BNC_TYPE = 1 THEN RTN.ACO_AMOUNT ELSE 0 END) AS BANK_QAYTARMA,

	USR_NAME

FROM OPR_INVOICE I

LEFT JOIN OPR_ACCOUNTS SLS
ON SLS.ACO_INVFICHENO = I.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY SBNC
ON SBNC.BNC_ID = SLS.ACO_BNCID

LEFT JOIN OPR_INVOICE IR
ON IR.INV_FICHENO = I.INV_RTNFICHENO

LEFT JOIN OPR_ACCOUNTS RTN
ON RTN.ACO_INVFICHENO = IR.INV_FICHENO

LEFT JOIN CRD_BANKCURRENCY RBNC
ON RBNC.BNC_ID = RTN.ACO_BNCID

LEFT JOIN CRD_STORAGES
ON STG_ID = I.INV_OBJ_ID

LEFT JOIN SYS_USERS_
ON USR_ID = I.INV_USR_ID

WHERE I.INV_DATETIME >= DATEADD(MONTH, -1, GETDATE())
AND I.INV_STATUS = 1

GROUP BY 
    I.INV_DATETIME,
	STG_ERPCODE,
	STG_NAME,
	I.INV_FICHENO,
	I.INV_RTNFICHENO,
	USR_NAME
	 
ORDER BY INV_DATETIME ASC;
